
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.objects.NativeString.toLowerCase;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * Pembuat :  Candra Julius Sinaga
 */
public class MyBiodata extends javax.swing.JFrame {

    /**
     * Created By Candra Julius Sinaga
     */
    public MyBiodata() {
        initComponents();
        setSize(660,520);
        setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        text3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tombol1 = new javax.swing.JRadioButton();
        tombol2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        Hobby = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        EditText = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        Tampilkan = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        babi = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        anjing = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        hapus1 = new javax.swing.JButton();
        simpan1 = new javax.swing.JButton();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        kudanil = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        monyet = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        data = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel6.setBackground(new java.awt.Color(255, 102, 102));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("   Nama Belakang");

        jTextField6.setText("jTextField1");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel14MouseDragged(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nama Depan");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 100, 90, 29);

        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });
        jPanel1.add(text1);
        text1.setBounds(140, 100, 186, 29);

        jLabel3.setBackground(new java.awt.Color(255, 102, 102));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("   Nama Belakang");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 140, 120, 29);

        text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text2ActionPerformed(evt);
            }
        });
        jPanel1.add(text2);
        text2.setBounds(140, 140, 186, 29);

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Biodata Diri");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\aa7j2-63s9t.png")); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\agwqp-aipp6.png")); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("<- Back");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("?");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 670, 70);

        jLabel4.setBackground(new java.awt.Color(255, 102, 102));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 180, 120, 29);

        text3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text3ActionPerformed(evt);
            }
        });
        jPanel1.add(text3);
        text3.setBounds(140, 180, 186, 29);

        jLabel5.setBackground(new java.awt.Color(255, 102, 102));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hobby");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 250, 120, 29);

        text4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text4ActionPerformed(evt);
            }
        });
        jPanel1.add(text4);
        text4.setBounds(140, 280, 186, 29);

        jLabel7.setBackground(new java.awt.Color(255, 102, 102));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Deskripsi");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 380, 120, 29);

        text5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text5ActionPerformed(evt);
            }
        });
        jPanel1.add(text5);
        text5.setBounds(140, 320, 186, 29);

        jLabel8.setBackground(new java.awt.Color(255, 102, 102));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Email");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 280, 120, 29);

        buttonGroup1.add(tombol1);
        tombol1.setText("Laki-Laki");
        tombol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol1ActionPerformed(evt);
            }
        });
        jPanel1.add(tombol1);
        tombol1.setBounds(140, 220, 80, 23);

        buttonGroup1.add(tombol2);
        tombol2.setText("Perempuan");
        tombol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol2ActionPerformed(evt);
            }
        });
        jPanel1.add(tombol2);
        tombol2.setBounds(230, 220, 90, 23);

        jLabel9.setBackground(new java.awt.Color(255, 102, 102));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Jenis Kelamin");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 220, 120, 29);

        Hobby.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Hobby.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Main Bola", "Musik", "Game", "Menulis", "Membaca", " " }));
        Hobby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HobbyActionPerformed(evt);
            }
        });
        jPanel1.add(Hobby);
        Hobby.setBounds(140, 250, 190, 23);

        EditText.setColumns(20);
        EditText.setRows(5);
        EditText.setText("Deskripsikan tentang diri anda");
        jScrollPane1.setViewportView(EditText);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 360, 200, 113);

        jLabel10.setBackground(new java.awt.Color(255, 102, 102));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("No HandPhone");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 320, 120, 29);

        Tampilkan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tampilkan.setText("Tampilkan");
        Tampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TampilkanActionPerformed(evt);
            }
        });
        jPanel1.add(Tampilkan);
        Tampilkan.setBounds(110, 480, 100, 23);

        Hapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        jPanel1.add(Hapus);
        Hapus.setBounds(220, 480, 90, 23);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(260, 500));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(null);

        babi.setBackground(new java.awt.Color(51, 0, 51));
        babi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(babi);
        babi.setBounds(0, 179, 310, 35);

        label5.setBackground(new java.awt.Color(51, 0, 51));
        label5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(label5);
        label5.setBounds(0, 82, 310, 35);

        jLabel13.setBackground(new java.awt.Color(51, 0, 51));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 123, 169, 0);

        label2.setBackground(new java.awt.Color(51, 0, 51));
        label2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(label2);
        label2.setBounds(0, 41, 310, 35);

        jLabel15.setBackground(new java.awt.Color(51, 0, 51));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 151, 169, 0);

        anjing.setBackground(new java.awt.Color(51, 0, 51));
        anjing.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(anjing);
        anjing.setBounds(0, 220, 310, 35);

        label3.setBackground(new java.awt.Color(51, 0, 51));
        label3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(label3);
        label3.setBounds(0, 150, 310, 30);

        hapus1.setText("Hapus");
        hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus1ActionPerformed(evt);
            }
        });
        jPanel2.add(hapus1);
        hapus1.setBounds(180, 380, 80, 23);

        simpan1.setText("Simpan");
        simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan1ActionPerformed(evt);
            }
        });
        jPanel2.add(simpan1);
        simpan1.setBounds(0, 380, 90, 23);

        label6.setBackground(new java.awt.Color(51, 0, 51));
        label6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(label6);
        label6.setBounds(0, 82, 206, 35);

        label7.setBackground(new java.awt.Color(51, 0, 51));
        label7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(label7);
        label7.setBounds(0, 82, 206, 35);

        label1.setBackground(new java.awt.Color(51, 0, 51));
        label1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(label1);
        label1.setBounds(0, 0, 310, 35);

        kudanil.setBackground(new java.awt.Color(51, 0, 51));
        kudanil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(kudanil);
        kudanil.setBounds(0, 120, 310, 30);

        jScrollPane3.setBackground(new java.awt.Color(51, 51, 255));

        monyet.setBackground(new java.awt.Color(102, 102, 255));
        monyet.setColumns(20);
        monyet.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        monyet.setRows(5);
        monyet.setBorder(null);
        jScrollPane3.setViewportView(monyet);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(0, 260, 310, 110);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(340, 100, 320, 400);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(220, 480, 90, 23);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Hapus");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(220, 480, 90, 23);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Hapus");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(220, 480, 90, 23);

        data.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jPanel1.add(data);
        data.setBounds(380, 80, 190, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 690, 533);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int mousex;
    int mousey;
    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text1ActionPerformed

    private void text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text2ActionPerformed

    private void text3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text3ActionPerformed

    private void text4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void text5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text5ActionPerformed

    private void tombol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol1ActionPerformed
        // TODO add your handling code here:
        if (tombol1.isSelected()) {
            
        }
    }//GEN-LAST:event_tombol1ActionPerformed

    private void tombol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombol2ActionPerformed

    private void HobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HobbyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HobbyActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        if (text1.getText().isEmpty() || text2.getText().isEmpty() || text3.getText().isEmpty() || text4.getText().isEmpty()
               || text5.getText().isEmpty() || EditText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Anda belum mengisi data, Terimakasih");
        }else{
      text1.setText("");
      text2.setText("");
      text3.setText("");
      text4.setText("");
      text5.setText("");
      EditText.setText("");
      Hobby.getSelectedItem().toString();
      tombol1.isSelected();
        
    }//GEN-LAST:event_HapusActionPerformed
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void TampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TampilkanActionPerformed
        // TODO add your handling code here:
        if (text1.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Nama Depan Masih Kosong");
        }else if (text2.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Nama Belakang Masih Kosong");
        }else if (text3.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Alamat Anda Masih Kosong");
        }else if (Hobby.getSelectedItem().toString().equals("Pilih")) {
        JOptionPane.showMessageDialog(this, "Ands belum memilih Hobby");
        }else if (text4.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Email Anda Masih Kosong");
        }else if (text5.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Nomor Telepon Anda Masih Kosong");
        }else if (EditText.getText().equalsIgnoreCase("Deskripsikan tentang diri anda")) {
            JOptionPane.showMessageDialog(this,"Anda Belum Ada Mengisi tentang diri anda");
        }
        else{
        label1.setText("Nama Depan          : " + toLowerCase(text1.getText()));
        label2.setText("Nama Belakang      : " + toLowerCase(text2.getText()));
        label5.setText("Alamat                  : " + toLowerCase(text3.getText()));
        if (tombol1.isSelected()) {
            kudanil.setText("Jenis Kelamin         : Laki-Laki");
        }else{
            kudanil.setText("Jenis Kelamin         : Perempuan");
        }
        label3.setText("Hobby                   : " + Hobby.getSelectedItem().toString());
        babi.setText("Email                     : " + toLowerCase(text4.getText()));
        anjing.setText("No HandPhone      : " + toLowerCase(text5.getText()));
        monyet.setText(toLowerCase(EditText.getText()));
        data.setText("Data Yang Ingin Anda Simpan");
        }
        
    }//GEN-LAST:event_TampilkanActionPerformed

    private void simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan1ActionPerformed
        // TODO add your handling code here:
        if (text1.getText().isEmpty() || text2.getText().isEmpty() ||text3.getText().isEmpty() || text4.getText().isEmpty() 
                || text5.getText().isEmpty() || EditText.getText().isEmpty() || label1.getText().isEmpty() || label2.getText().isEmpty() || label3.getText().isEmpty()||label5.getText().isEmpty()
                || monyet.getText().isEmpty() || data.getText().isEmpty() || babi.getText().isEmpty() ) {
                JOptionPane.showMessageDialog(this ," Anda belum menampilkan data \n Data anda ada yang belum diisi, Silahkan anda cek lagi Terimakasih ");
                
        }else{
        String bangsat = "Apakah anda ingin menyimpan data tesebut? ";
        int siapa = JOptionPane.showConfirmDialog(this, bangsat);
        label1.setText("Nama Depan          : " + toLowerCase(text1.getText()));
        label2.setText("Nama Belakang      : " + toLowerCase(text2.getText()));
        label5.setText("Alamat                  : " + toLowerCase(text3.getText()));
        if (tombol1.isSelected()) {
            kudanil.setText("Jenis Kelamin         : Laki-Laki");
        }else{
            kudanil.setText("Jenis Kelamin         : Perempuan");
        }
        label3.setText("Hobby                   : " + Hobby.getSelectedItem().toString());
        babi.setText("Email                     : " + toLowerCase(text4.getText()));
        anjing.setText("No HandPhone      : " + toLowerCase(text5.getText()));
        monyet.setText(toLowerCase(EditText.getText()));
        data.setText("Data Yang Ingin Anda Simpan");
//            if (!label1.getText().isEmpty() || !label12.getText().isEmpty() || !label5.getText().isEmpty() || !label3.getText().isEmpty() 
//                || !babi.getText().isEmpty() || !anjing.getText().isEmpty() || !monyet.getText().isEmpty() || !data.getText().isEmpty()) {
//                label1.setText("Nama Depan          : " + toLowerCase(text1.getText()));
//        label2.setText("Nama Belakang      : " + toLowerCase(text2.getText()));
//        label5.setText("Alamat                  : " + toLowerCase(text3.getText()));
//        if (tombol1.isSelected()) {
//            kudanil.setText("Jenis Kelamin         : Laki-Laki");
//        }else{
//            kudanil.setText("Jenis Kelamin         : Perempuan");
//        }
//        label3.setText("Hobby                   : " + Hobby.getSelectedItem().toString());
//        babi.setText("Email                     : " + toLowerCase(text4.getText()));
//        anjing.setText("No HandPhone      : " + toLowerCase(text5.getText()));
//        monyet.setText(toLowerCase(EditText.getText()));
//        data.setText("Data Yang Ingin Anda Simpan");
//        
//            }
        switch(siapa){
            case JOptionPane.YES_OPTION :
        // menyimpan data1
      label1.setText("");
        label2.setText("");
        label5.setText("");
        if (tombol1.isSelected()) {
            kudanil.setText("");
        }else{
            kudanil.setText("");
        }
        label3.setText("");
        babi.setText("");
        anjing.setText("");
        monyet.setText("");
        data.setText("");
        // menyimpan data2
        text1.setText("");
      text2.setText("");
      text3.setText("");
      text4.setText("");
      text5.setText("");
      EditText.setText("");
       Hobby.getSelectedItem().toString().isEmpty();
      tombol1.isSelected();
      JOptionPane.showMessageDialog(this, "Data anda Telah disimpan");
        break;
            case JOptionPane.NO_OPTION :
                JOptionPane.showMessageDialog(this, "Data tidak disimpan");
        label1.setText("Nama Depan          : " + toLowerCase(text1.getText()));
        label2.setText("Nama Belakang      : " + toLowerCase(text2.getText()));
        label5.setText("Alamat                  : " + toLowerCase(text3.getText()));
        if (tombol1.isSelected()) {
            kudanil.setText("Jenis Kelamin         : Laki-Laki");
        }else{
            kudanil.setText("Jenis Kelamin         : Perempuan");
        }
        label3.setText("Hobby                   : " + Hobby.getSelectedItem().toString());
        babi.setText("Email                     : " + toLowerCase(text4.getText()));
        anjing.setText("No HandPhone      : " + toLowerCase(text5.getText()));
        monyet.setText(toLowerCase(EditText.getText()));
        data.setText("Data Yang Ingin Anda Simpan");
        break;    
        }
        }
    }//GEN-LAST:event_simpan1ActionPerformed

    private void hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus1ActionPerformed
        // TODO add your handling code here:
        if (label1.getText().isEmpty() || label2.getText().isEmpty() || label5.getText().isEmpty() || kudanil.getText().isEmpty()
               || label3.getText().isEmpty() || babi.getText().isEmpty() || anjing.getText().isEmpty() || monyet.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Anda belum mengisi data, TerimaKasih ");
        }else{
        label1.setText("");
        label2.setText("");
        label5.setText("");
        if (tombol1.isSelected()) {
            kudanil.setText("");
        }else{
            kudanil.setText("");
        }
        label3.setText("");
        babi.setText("");
        anjing.setText("");
        monyet.setText("");
        data.setText("");
        }
    }//GEN-LAST:event_hapus1ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
    this. setState(JFrame.ICONIFIED);
        
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        int buaya = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin keluar");
        switch(buaya){
            case JOptionPane.YES_OPTION:
        this.dispose();
        System.exit(0);
        break;
            case JOptionPane.NO_OPTION :
            JOptionPane.showMessageDialog(this, "Anda tidak keluar");
            break;
            default:
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

    }//GEN-LAST:event_formMouseDragged

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling c
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this. setLocation(x -mousex, y -mousey);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        // TODO add your handling c
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this. setLocation(x -mousex, y -mousey);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling c
        int mouse = evt.getXOnScreen();
        int moused = evt.getYOnScreen();
        this. setLocation(mouse -mousex,moused -mousey);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jLabel14MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

    }//GEN-LAST:event_formMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        // TODO add your handling code here:
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        Login manusia = new Login();
        manusia.setSize(400,350);
        manusia.setLocationRelativeTo(null);
        manusia.setVisible(true);
        this. dispose();
        pack();
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyBiodata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea EditText;
    private javax.swing.JButton Hapus;
    private javax.swing.JComboBox<String> Hobby;
    private javax.swing.JButton Tampilkan;
    private javax.swing.JLabel anjing;
    private javax.swing.JLabel babi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel data;
    private javax.swing.JButton hapus1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel kudanil;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JTextArea monyet;
    private javax.swing.JButton simpan1;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    private javax.swing.JTextField text5;
    private javax.swing.JRadioButton tombol1;
    private javax.swing.JRadioButton tombol2;
    // End of variables declaration//GEN-END:variables
}
